### ISSUE TITLE
Camera type mirrored doesn't allow for zooming

### ISSUE THREAD

**Issue by RTMecha** [Keksuccino/JustZoom#23]
I noticed in the ZoomHandler.java file, it prevents zooming if the camera type is mirrored. Is there an issue with zooming when the camera is facing the player?

**Comment by Keksuccino** [comment]
As you said, it's disabled by design. I make zooming in third-person possible by switching to first-person on zoom, so you don't just see the player's head when zooming. This doesn't work for mirrored third-person, because you would look behind you when zooming. I could also make the player not render when zooming, but I decided not to do that for now, to keep the code as simple as possible.
